### ISSUE TITLE
İletişim

### ISSUE THREAD

**Issue by hawanbeats** [misagul/freeCheggAnswerDcBot#1]
Merhabalar hocam. Nasılsınız? Sizinle nasıl iletişime geçebilirim acaba?

**Comment by misagul** [comment]
> Merhabalar hocam. Nasılsınız? Sizinle nasıl iletişime geçebilirim acaba?
Discord strix#2371
İnstagram m_isagul
Kod ile ilgili bir şeyler soracaksanız pek yardımcı olamayabilirim. Python konusunda yeniyim henüz.
